### ISSUE TITLE
[Feature] Documentation additions [sf#3]

### ISSUE THREAD

**Issue by meneguzzi** [pucrs-automated-planning/javagp#18]
**Reported by schapel on 2010-10-17 22:34 UTC**
JavaGP release notes should document:
- the dependence JavaGP on Jason and JavaCC, and that these JAR files need to be placed in the lib directory
- the assumption of JavaGP that ground terms bound to two different variables are distinct (e.g. in walk(X,Y) X and Y cannot be bound to the same ground term)
- the lack of the closed-world assumption, which means that negated preconditions that hold in the initial state must be explicitly stated
- using the switch -Mmx2g to give JavaGP more heap space will help JavaGP complete longer plans

**Comment by meneguzzi** [comment]
**Commented by meneguzzi on 2010-10-28 03:47 UTC**
I agree with the need for the feature request and I will be working on it shortly.

**Comment by meneguzzi** [comment]
**Updated by meneguzzi on 2010-10-28 03:47 UTC**
- **labels**:  --> Documentation

**Comment by meneguzzi** [comment]
**Updated by meneguzzi on 2010-10-28 03:48 UTC**
- **assigned_to**: nobody --> meneguzzi

**Comment by Maumagnaguagno** [comment]
The supported `:requirements` should also be part of README, but I do not know which ones are currently supported.
**Never equal variables** and **lack of closed-world assumption**  are unexpected behavior, could this be fixed?

**Comment by meneguzzi** [comment]
Mauricio, what do you mean by _Never equal variables_?
I think **closed world assumption** is an available option, even if we currently have problems with it as in issues #23 and #10, I will try to address these issues in the README today, when it's done I will ask you guys to check it.

**Comment by Maumagnaguagno** [comment]
Never equal variables are different parameters never unified to the same object/equality.
But I discovered other planners follow this behavior, ~~should just be explicit in the README~~.
I see you updated the README :smile:!
